import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PricingProvider } from "./providers/PricingProvider";

const interFont = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pricing simulator",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.className} antialiased`}>
        <PricingProvider>{children}</PricingProvider>
      </body>
    </html>
  );
}
